### ISSUE TITLE
Две буквы "ss" в протоколе "httpss"

### ISSUE THREAD

**Issue by vprivaloff** [floor12/yii2-metamaster#1]
Здравствуйте. В мета-тегах появилось две буквы в протоколе, выглядит это вот так `<meta property="og:url" content="httpss://site.com/">`. Пробовал в параметрах установить ''protocol' => 'https'`. Не помогло. http работает исправно

**Comment by floor12** [comment]
Да, вижу проблему. Сегодня-завтра выйдет новая версия. Хочу сразу и тест на эту проблему сделать.

**Comment by vprivaloff** [comment]
> Да, вижу проблему. Сегодня-завтра выйдет новая версия. Хочу сразу и тест на эту проблему сделать.

Спасибо большое. Очень хороший компонент!

**Comment by floor12** [comment]
Написал тест на это случай и пофиксил соответствующий метод. Обновляйтесь на dev-master или версию 1.1.4.

**Comment by vprivaloff** [comment]
Обновил до 1.1.4. Проблема "httpss" по прежнему наблюдается
Пробовал убрать/поставить/изменить 'protocol' => 'https'. Не помогло.
При этом этот тег "<meta property="og:url" content="https://" отображается правильно

**Comment by floor12** [comment]
Так, если в `<meta property="og:url` все в порядке, то где тогда проблема с httpss? 
Где именно проявляется и какой вызов модуля.
В принципе, ты можешь и сам посмотреть что там происходит, там класс всего один и простой )

**Comment by vprivaloff** [comment]
Да, вчера поправил класс. Просто придется тогда во всех проектах вручную менять.
Проблема кроется где-то вот в этих строчках

`196: $this->view->registerMetaTag(['name' => 'twitter:domain', 'content' => str_replace(['http', 'httpss'], $this->protocol, $this->request->hostInfo)]);`

`245: $imageUrl = str_replace(['http', 'httpss'], $this->protocol, $this->request->hostInfo . $image);`

Видишь я поменял https на httpss и тогда все отображается корректно.

По поводу вызова все стандартно

В контроллере:
Yii::$app->metamaster
	->setTitle("Заголовок")
	->setDescription("Описание")
	->setImage('/uploads/img/home.jpg')
	->register(Yii::$app->getView());

В конфиге:
'metamaster' => [
 'class' => 'floor12\metamaster\MetaMaster',
 'siteName' => 'Name',
 'defaultImage' => '',
],

**Comment by floor12** [comment]
Так, это был мой очередной косяк. Метод-то я написал для замены, и  протестил его. А внедрил его не везде. Версия 1.1.5 решает все проблемы.

**Comment by vprivaloff** [comment]
Подтверждаю! С версией 1.1.5 все работает исправно! Спасибо!
