### ISSUE TITLE
setKeywords

### ISSUE THREAD

**Issue by VolkAlex** [floor12/yii2-metamaster#4]
Hi! Thanks for your work, just tell me please, why setKeywords is deprecated?

**Comment by floor12** [comment]
Hello my friend.
According to latest web and  seo standarts meta-keywords does not need to be in any html document.
All search engines is ignoring it and SEO managers too.

https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag

**Comment by VolkAlex** [comment]
Okay, thanks!
